### ISSUE TITLE
常仁玉

### ISSUE THREAD

**Issue by hellokity520** [ukui/hacking-test#251]
I am a sophomore at the School of Computer and Information Engineering at Henan University.
I want to learn from Yulin, and I also want to participate in the excellent Qilin community activities and project development.
Then I want to learn about the specific knowledge needs system.
1.图标有互相遮盖现象，可以适当改进图标布局，增加兼容性
2.一些按钮选项点击无效(＾－＾)V，比如在桌面右键后更改分辨率等没有提示和响应
3.界面，特别是应用打开后，不是很流畅，视觉感官有些生硬
4.还是希望系统更加纯净一些
5.希望提供更多使用文档
6.大小写锁定问题，大小写切换不习惯
7.磁盘分析打开速度慢或打不开
8.丰富现阶段软件库，提供常见软件的下载
9.加大宣传力度，使更多国人可以了解到，国产的Linux系统
10.优化加载速度，使使用更加流畅
11.简化安装过程，使新手更易使用
12.对于现有的应用，经常更新，优化体验
13.加快新应用的开发进程
14.文件路径出现\\\的异常情况
15.天气软件出现没有全部显示信息或信息残余现象
16.有一个疑问，是否与UBUNTU原生系统的操作指令相同？

**Comment by hellokity520** [comment]
17.WPS兼容性不好

**Comment by readlnh** [comment]
指令是相同的，我们是桌面操作系统，也就是说除了桌面基本都是相同的
