### ISSUE TITLE
网络状态显示错误

### ISSUE THREAD

**Issue by LhdDream** [ukui/hacking-test#28]
网络工具显示可以联通，但是无法使用ping 命令显示不允许
测试用例：
1，打开电脑
2，点击状态栏wifi连接图标
3，检查任务栏的网络状态是否与网络工具中的网络状态一致。
右下角显示wifi连接图标，点开工具后，显示网络已关闭，wifi已关闭
预期结果：通过

实际结果：网络工具连接状态显示错误
1、Open network tool
2、Turn on the network
3、Turn off network connection
开启网络连接后，无法再关闭网络和wifi

**Comment by readlnh** [comment]
这个应该是docker容器的问题
