### ISSUE TITLE
对蓝牙管理器的提议

### ISSUE THREAD

**Issue by slbqsa** [ukui/hacking-test#45]
2.在Ubuntu kylin 19.04版中，蓝牙连接不可用。每次打开，都会提示连接至blueZ失败，尝试搜索蓝牙blueberry 但文件中没有，在终端中输入 sudo apt-get install blueman下载blueman也不可以。

**Comment by readlnh** [comment]
是在黑客松平台吗还是物理机，请叙述下具体的情形
