### ISSUE TITLE
关于 g++

### ISSUE THREAD

**Issue by okokme** [ukui/hacking-test#58]
In file included from /usr/include/x86_64-linux-gnu/c++/8/bits/os_defines.h:39,
                 from /usr/include/x86_64-linux-gnu/c++/8/bits/c++config.h:508,
                 from /usr/include/c++/8/iostream:38,
                 from a.cpp:1:
/usr/include/features.h:446:12: fatal error: sys/cdefs.h: \u6ca1\u6709\u90a3\u4e2a\u6587\u4ef6\u6216\u76ee\u5f55
 #  include <sys/cdefs.h>
            ^~~~~~~~~~~~~

**Comment by readlnh** [comment]
sudo apt-get purge libc6-dev
sudo apt-get install libc6-dev
sudo apt-get install libc6-dev-i386
