### ISSUE TITLE
任务栏

### ISSUE THREAD

**Issue by LhdDream** [ukui/hacking-test#85]
任务栏
   右下角的显示桌面按钮，鼠标放上去后WPS软件会最小化，而其他程序窗口只会隐藏，移走鼠标后重新显示。
右键——任务栏设置——任务栏消失后再出现，设置窗口未打开。左侧的按钮不可用后通过这个方式又可以使用了（可以点击了）。
   任务栏图标排列不紧凑，没有充分利用空间，开始菜单与右边的图标存在间隙，时间与左右两边存在间隙，窗口占满任务栏时只能在窗口上的右键，无法打开任务栏右键的设置（建议此时右键设置可以放置到开始菜单右键设置一起）。
   任务栏左下角开始按钮与右边间距空隙较大，可以做到可以放置按钮紧挨着，像其他图标一样。deepin系统的任务栏就做的比较好，（高效任务栏像win7）可以借鉴。既然仿Windows就仿的更像一点，仿的界面越接近，可以迎合用户的使用习惯，更容易上手，且要做到更易用，效率更高，就像WPS一样迎合用户需求。WPS在这方面就做的很好，与时俱进。觉得不能搞得有一点像，而体验还很差。要不就要完全开创自己的一套，其他界面可以给用户选择。

**Comment by readlnh** [comment]
这个说得太好了，我一直想吐槽
